version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Configuration optionnelle pour le développement
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge