apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80       # Port exposé au monde extérieur
      targetPort: 8080 # Port sur lequel le frontend écoute dans le conteneur
